name: Backend main workflow
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
jobs:
  run-tests-and-deploy:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install dependencies
        run: npm install
      - name: Compile TypeScript
        run: npx tsc
      - name: Run tests
        run: npm test
      - name: Deploy to Azure
        if: github.ref == 'refs/heads/18-azure-deployment'
        run: |
          mkdir secrets
          echo "${{ secrets.FIREBASE_CONFIG }}" > secrets/firebase.json
          echo "${{ secrets.ENVIRONMENT_VARIABLES }}" > .env
          docker build -t movesense-backend .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u movesensemetropolia --password-stdin movesensemetropolia.azurecr.io
          docker tag movesense-backend movesensemetropolia.azurecr.io/movesense-backend
          docker push movesensemetropolia.azurecr.io/movesense-backend
          docker logout
